package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	basename := file.GeneratedFilenamePrefix
	idx := strings.LastIndex(basename, "/")
	if idx != -1 {
		basename = basename[idx+1:]
	}
	filename := basename + ".flap.dart"

	g := gen.NewGeneratedFile(filename, "")

	g.P("// Code generated by protoc-gen-dart-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("import 'package:flap/bridge/bridge.dart';")
	g.P("import 'package:flap/bridge/connect_transport.dart';")

	dartProtoImport := fmt.Sprintf("import '%s.pb.dart';", basename)
	g.P(dartProtoImport)

	// Import dependencies if they contain messages used here
	importCount := file.Desc.Imports().Len()
	for i := 0; i < importCount; i++ {
		dep := file.Desc.Imports().Get(i)
		depPath := strings.TrimSuffix(dep.Path(), ".proto")
		idx = strings.LastIndex(depPath, "/")
		if idx != -1 {
			depPath = depPath[idx+1:]
		}
		g.P("import '", depPath, ".pb.dart';")
	}

	g.P()

	for _, service := range file.Services {
		generateService(g, service)
	}
}

func generateService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName
	clientName := serviceName + "Client"

	g.P("class ", clientName, " {")
	g.P("  final BridgeTransport _transport;")
	g.P()
	g.P("  ", clientName, "(Bridge bridge) : _transport = BridgeTransport(bridge);")
	g.P()

	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue // Not supported
		}

		reqName := method.Input.GoIdent.GoName
		resName := method.Output.GoIdent.GoName
		methodName := toCamelCase(method.GoName)
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())

		if method.Desc.IsStreamingServer() {
			g.P("  Stream<", resName, "> ", methodName, "(", reqName, " request) async* {")
			g.P("    yield* _transport.stream(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		} else {
			g.P("  Future<", resName, "> ", methodName, "(", reqName, " request) async {")
			g.P("    return _transport.unary(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		}
	}
	g.P("}")
}

func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
