package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0

	var normalServices, reverseServices []*protogen.Service
	for _, svc := range file.Services {
		if strings.HasSuffix(string(svc.Desc.Name()), "ReverseService") {
			reverseServices = append(reverseServices, svc)
		} else {
			normalServices = append(normalServices, svc)
		}
	}

	if len(normalServices) == 0 && len(reverseServices) == 0 && !hasPush {
		return
	}

	basename := file.GeneratedFilenamePrefix
	idx := strings.LastIndex(basename, "/")
	if idx != -1 {
		basename = basename[idx+1:]
	}
	filename := basename + ".flap.dart"

	g := gen.NewGeneratedFile(filename, "")

	g.P("// Code generated by protoc-gen-dart-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()

	if hasPush || len(reverseServices) > 0 {
		g.P("import 'dart:async';")
		g.P()
	}
	needsBridge := len(normalServices) > 0 || len(reverseServices) > 0
	if needsBridge {
		g.P("import 'package:flap/bridge/bridge.dart';")
	}
	if len(normalServices) > 0 {
		g.P("import 'package:flap/bridge/transport.dart';")
	}
	if len(reverseServices) > 0 {
		g.P("import 'package:fixnum/fixnum.dart';")
	}

	dartProtoImport := fmt.Sprintf("import '%s.pb.dart';", basename)
	g.P(dartProtoImport)

	importCount := file.Desc.Imports().Len()
	for i := 0; i < importCount; i++ {
		dep := file.Desc.Imports().Get(i)
		depPath := strings.TrimSuffix(dep.Path(), ".proto")
		idx = strings.LastIndex(depPath, "/")
		if idx != -1 {
			depPath = depPath[idx+1:]
		}
		g.P("import '", depPath, ".pb.dart';")
	}

	if hasPush || len(reverseServices) > 0 {
		g.P("import 'core.pb.dart';")
	}

	g.P()

	for _, svc := range normalServices {
		generateNormalServiceClient(g, svc)
	}

	for _, svc := range reverseServices {
		generateReverseServiceHandler(g, svc)
	}

	if hasPush {
		generatePushHandler(g, basename, pushMessages, reverseServices)
	} else if len(reverseServices) > 0 {
		// PushHandler is needed even without Push messages to dispatch reverse calls
		generatePushHandler(g, basename, nil, reverseServices)
	}
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

func generatePushHandler(g *protogen.GeneratedFile, basename string, pushMessages []*protogen.Message, reverseServices []*protogen.Service) {
	hasReverse := len(reverseServices) > 0

	g.P("/// PushHandler dispatches incoming [Push] messages to typed streams")
	g.P("/// and handles Go->Dart->Go ReverseService calls.")
	g.P("class PushHandler {")
	g.P("  late final StreamSubscription<Push> _subscription;")
	if hasReverse {
		g.P("  final Bridge _bridge = Bridge();")
	}
	g.P()

	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		controllerName := "_" + strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:] + "Controller"
		g.P("  final _StreamBroadcast<", msgName, "> ", controllerName, " = _StreamBroadcast();")
	}

	// Handler fields for each ReverseService
	for _, svc := range reverseServices {
		handlerName := svc.GoName + "Handler"
		fieldName := "_" + toCamelCase(svc.GoName) + "Handler"
		g.P("  ", handlerName, "? ", fieldName, ";")
	}

	g.P()
	g.P("  PushHandler(Stream<Push> pushStream) {")
	g.P("    _subscription = pushStream.listen(_dispatch);")
	g.P("  }")
	g.P()

	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		streamName := strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:]
		controllerName := "_" + streamName + "Controller"
		g.P("  Stream<", msgName, "> get ", streamName, " => ", controllerName, ".stream;")
	}

	// Setter for each ReverseService handler
	for _, svc := range reverseServices {
		handlerName := svc.GoName + "Handler"
		fieldName := "_" + toCamelCase(svc.GoName) + "Handler"
		setterName := "set" + svc.GoName + "Handler"
		g.P()
		g.P("  void ", setterName, "(", handlerName, " handler) {")
		g.P("    ", fieldName, " = handler;")
		g.P("  }")
	}

	g.P()
	g.P("  void _dispatch(Push push) {")

	if hasReverse {
		g.P("    if (push.reversePort != Int64.ZERO) {")
		g.P("      _dispatchReverse(push);")
		g.P("      return;")
		g.P("    }")
	}

	g.P("    switch (push.type) {")
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fullName := string(msg.Desc.FullName())
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		streamName := strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:]
		controllerName := "_" + streamName + "Controller"
		g.P("      case '", fullName, "':")
		g.P("        ", controllerName, ".add(", msgName, ".fromBuffer(push.payload));")
		g.P("        break;")
	}
	g.P("      default:")
	g.P("        break;")
	g.P("    }")
	g.P("  }")

	if hasReverse {
		g.P()
		g.P("  void _dispatchReverse(Push push) {")
		g.P("    Future<List<int>>? fut;")
		g.P("    switch (push.type) {")
		for _, svc := range reverseServices {
			fieldName := "_" + toCamelCase(svc.GoName) + "Handler"
			for _, method := range svc.Methods {
				if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
					continue
				}
				fullPath := fmt.Sprintf("/%s/%s", svc.Desc.FullName(), method.Desc.Name())
				inName := method.Input.GoIdent.GoName
				outName := method.Output.GoIdent.GoName
				methodName := toCamelCase(method.GoName)
				g.P("      case '", fullPath, "':")
				g.P("        if (", fieldName, " != null) {")
				g.P("          final req = ", inName, ".fromBuffer(push.payload);")
				g.P("          fut = ", fieldName, "!.", methodName, "(req)")
				g.P("              .then((resp) => resp.writeToBuffer());")
				g.P("        }")
				g.P("        break;")
				_ = outName
			}
		}
		g.P("    }")
		g.P("    if (fut == null) return;")
		g.P("    fut.then((payload) {")
		g.P("      _bridge.sendReverseResponse(push.reversePort, payload);")
		g.P("    });")
		g.P("  }")
	}

	g.P()
	g.P("  void dispose() {")
	g.P("    _subscription.cancel();")
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		controllerName := "_" + strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:] + "Controller"
		_ = msgName
		g.P("    ", controllerName, ".close();")
	}
	g.P("  }")
	g.P("}")
	if len(pushMessages) > 0 {
		g.P()
		g.P("class _StreamBroadcast<T> {")
		g.P("  final _controller = StreamController<T>.broadcast();")
		g.P("  Stream<T> get stream => _controller.stream;")
		g.P("  void add(T value) => _controller.add(value);")
		g.P("  void close() => _controller.close();")
		g.P("}")
	}
}

// generateReverseServiceHandler generates the abstract class Dart must implement.
func generateReverseServiceHandler(g *protogen.GeneratedFile, service *protogen.Service) {
	handlerName := service.GoName + "Handler"

	g.P("/// ", handlerName, " is the Dart-side handler for the Go->Dart->Go ", service.GoName, ".")
	g.P("/// Implement this and register it via PushHandler.set", service.GoName, "Handler().")
	g.P("abstract class ", handlerName, " {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		inName := method.Input.GoIdent.GoName
		outName := method.Output.GoIdent.GoName
		methodName := toCamelCase(method.GoName)
		g.P("  Future<", outName, "> ", methodName, "(", inName, " request);")
	}
	g.P("}")
	g.P()
}

// generateNormalServiceClient generates the Dart client for a normal (Dart->Go) service.
func generateNormalServiceClient(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName
	clientName := serviceName + "Client"

	g.P("class ", clientName, " {")
	g.P("  final Transport _transport;")
	g.P()
	g.P("  ", clientName, "(Bridge bridge) : _transport = Transport(bridge);")
	g.P()

	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}

		reqName := method.Input.GoIdent.GoName
		resName := method.Output.GoIdent.GoName
		methodName := toCamelCase(method.GoName)
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())

		if method.Desc.IsStreamingServer() {
			g.P("  Stream<", resName, "> ", methodName, "(", reqName, " request) async* {")
			g.P("    yield* _transport.stream(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		} else {
			g.P("  Future<", resName, "> ", methodName, "(", reqName, " request) async {")
			g.P("    return _transport.unary(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		}
	}
	g.P("}")
}

func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
