package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	var flags flagSet
	opts := protogen.Options{
		ParamFunc: flags.Set,
	}
	opts.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, flags.corePkg)
		}
		return nil
	})
}

type flagSet struct {
	corePkg string
}

func (f *flagSet) Set(name, value string) error {
	switch name {
	case "core_pkg":
		f.corePkg = value
	}
	return nil
}

func generateFile(gen *protogen.Plugin, file *protogen.File, corePkg string) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0

	var normalServices, reverseServices []*protogen.Service
	for _, svc := range file.Services {
		if strings.HasSuffix(string(svc.Desc.Name()), "ReverseService") {
			reverseServices = append(reverseServices, svc)
		} else {
			normalServices = append(normalServices, svc)
		}
	}

	if len(normalServices) == 0 && len(reverseServices) == 0 && !hasPush {
		return
	}

	if corePkg == "" {
		corePkg = "github.com/nosuta/godash/pb"
	}

	filename := file.GeneratedFilenamePrefix + ".flap.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-godash. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	alias := "core"

	g.P("import (")
	needsContext := len(normalServices) > 0 || len(reverseServices) > 0
	if needsContext {
		g.P(`	"context"`)
	}
	if hasPush {
		g.P(`	"fmt"`)
	}
	g.P()
	g.P(`	core "`, corePkg, `"`)
	g.P(")")
	g.P()

	for _, svc := range normalServices {
		generateNormalService(g, svc, alias)
	}

	for _, svc := range reverseServices {
		generateReverseService(g, svc, alias)
	}

	if hasPush {
		emitPushHelpers(g, pushMessages, alias)
	}
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

// emitPushHelpers generates SendPushXxx functions for each Push-prefixed message.
func emitPushHelpers(g *protogen.GeneratedFile, pushMessages []*protogen.Message, alias string) {
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fullName := string(msg.Desc.FullName())
		funcName := "Send" + msgName
		g.P("// ", funcName, " sends a ", msgName, " message to Dart as a fire-and-forget push.")
		g.P("func ", funcName, "(msg *", msgName, ") error {")
		g.P(`	if core.PushFn == nil {`)
		g.P(`		return fmt.Errorf("pushFn is not set")`)
		g.P(`	}`)
		g.P(`	return core.PushFn(&core.Push{Type: "`, fullName, `", Payload: core.MarshalHelper(msg)})`)
		g.P("}")
		g.P()
	}
}

// generateNormalService generates the server-side handler interface and router (Dart->Go).
func generateNormalService(g *protogen.GeneratedFile, service *protogen.Service, alias string) {
	serviceName := service.GoName
	baseName := strings.TrimSuffix(serviceName, "Service")
	interfaceName := baseName + "RPCHandler"
	handleFuncName := "Handle" + baseName + "RPC"

	g.P("// ", interfaceName, " is the server interface for the ", serviceName, " service.")
	g.P("type ", interfaceName, " interface {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		if method.Desc.IsStreamingServer() {
			g.P("\t", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ", ch chan<- *core.Response) error")
		} else {
			g.P("\t", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error)")
		}
	}
	g.P("}")
	g.P()

	g.P("func ", handleFuncName, "(ctx context.Context, req *core.RpcRequest, ch chan<- *core.Response, handler ", interfaceName, ") bool {")
	g.P("\tswitch req.Path {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		g.P("\tcase ", `"`+fullPath+`"`, ":")
		g.P("\t\tvar msg ", method.Input.GoIdent.GoName)
		g.P("\t\tif err := msg.UnmarshalVT(req.Payload); err != nil {")
		g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 400, Message: err.Error()}}}")
		g.P("\t\t\treturn true")
		g.P("\t\t}")
		g.P()
		if method.Desc.IsStreamingServer() {
			g.P("\t\tif err := handler.", method.GoName, "(ctx, &msg, ch); err != nil {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 500, Message: err.Error()}}}")
			g.P("\t\t}")
		} else {
			g.P("\t\tresp, err := handler.", method.GoName, "(ctx, &msg)")
			g.P("\t\tif err != nil {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 500, Message: err.Error()}}}")
			g.P("\t\t} else {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_RpcResponse{RpcResponse: &core.RpcResponse{Payload: core.MarshalHelper(resp)}}}")
			g.P("\t\t}")
		}
		g.P("\t\treturn true")
	}
	g.P("\t}")
	g.P("\treturn false")
	g.P("}")
	g.P()
}

// generateReverseService generates the client-side caller (Go->Dart) using ReverseCall.
// Only unary methods are supported (no streaming from Go side).
func generateReverseService(g *protogen.GeneratedFile, service *protogen.Service, alias string) {
	serviceName := service.GoName

	g.P("// ", serviceName, "Caller contains generated ReverseCall helpers for ", serviceName, ".")
	g.P("// Each function sends a Push to Dart and waits for a ReverseResponse.")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue // streaming not supported for ReverseService
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		funcName := strings.TrimSuffix(serviceName, "ReverseService") + "ReverseRPC" + method.GoName
		inName := method.Input.GoIdent.GoName
		outName := method.Output.GoIdent.GoName

		g.P("func ", funcName, "(ctx context.Context, req *", inName, ") (*", outName, ", error) {")
		g.P(`	push := &core.Push{Type: "`, fullPath, `", Payload: core.MarshalHelper(req)}`)
		g.P("\tpayload, err := core.ReverseCallFn(ctx, push)")
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\tvar resp ", outName)
		g.P("\tif err := resp.UnmarshalVT(payload); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &resp, nil")
		g.P("}")
		g.P()
	}
}
