name: web_internal
description: "used only for the web platform"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
