package main

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		sharedEmitted := map[string]bool{}
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, sharedEmitted)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File, sharedEmitted map[string]bool) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0

	var normalServices, reverseServices []*protogen.Service
	for _, svc := range file.Services {
		if strings.HasSuffix(string(svc.Desc.Name()), "ReverseService") {
			reverseServices = append(reverseServices, svc)
		} else {
			normalServices = append(normalServices, svc)
		}
	}

	if len(normalServices) == 0 && len(reverseServices) == 0 && !hasPush {
		return
	}

	generateSharedFile(gen, file, sharedEmitted)

	filename := file.GeneratedFilenamePrefix + ".flap.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsContext := len(normalServices) > 0 || len(reverseServices) > 0
	if needsContext {
		g.P("import (")
		g.P(`	"context"`)
		g.P(")")
		g.P()
	}

	for _, svc := range normalServices {
		generateNormalService(g, svc)
	}

	for _, svc := range reverseServices {
		generateReverseService(g, svc)
	}

	if hasPush {
		emitPushHelpers(g, pushMessages)
	}
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

// emitPushHelpers generates NewPushXxx constructor helpers for each Push-prefixed message.
func emitPushHelpers(g *protogen.GeneratedFile, pushMessages []*protogen.Message) {
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fullName := string(msg.Desc.FullName())
		g.P("// New", msgName, " wraps ", msgName, " into a Push message.")
		g.P("func New", msgName, "(msg *", msgName, ") *Push {")
		g.P(`	return &Push{Type: "`, fullName, `", Payload: marshalHelper(msg)}`)
		g.P("}")
		g.P()
	}
}

func generateSharedFile(gen *protogen.Plugin, file *protogen.File, sharedEmitted map[string]bool) {
	outDir := path.Dir(file.GeneratedFilenamePrefix)
	if sharedEmitted[outDir] {
		return
	}
	sharedEmitted[outDir] = true

	filename := path.Join(outDir, "marshal_shared.flap.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import \"context\"")
	g.P()
	g.P("func marshalHelper(msg interface{ MarshalVT() ([]byte, error) }) []byte {")
	g.P("	b, err := msg.MarshalVT()")
	g.P("	if err != nil {")
	g.P("		panic(err)")
	g.P("	}")
	g.P("	return b")
	g.P("}")
	g.P()
	g.P("// ReverseCallFn is called by generated ReverseService functions to send a Push")
	g.P("// to Dart and wait for a ReverseResponse. Set this at startup (e.g. in rpc.Init).")
	g.P("var reverseCallFn func(ctx context.Context, push *Push) ([]byte, error)")
	g.P()
	g.P("// SetReverseCallFn wires the ReverseService caller. Called once during init.")
	g.P("func SetReverseCallFn(fn func(ctx context.Context, push *Push) ([]byte, error)) {")
	g.P("	reverseCallFn = fn")
	g.P("}")
	g.P()
}

// generateNormalService generates the server-side handler interface and router (Dart->Go).
func generateNormalService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName
	interfaceName := serviceName + "Handler"

	g.P("// ", interfaceName, " is the server interface for the ", serviceName, " service.")
	g.P("type ", interfaceName, " interface {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		if method.Desc.IsStreamingServer() {
			g.P("	", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ", ch chan<- *Response) error")
		} else {
			g.P("	", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error)")
		}
	}
	g.P("}")
	g.P()

	g.P("func Handle", serviceName, "(ctx context.Context, req *RpcRequest, ch chan<- *Response, handler ", interfaceName, ") bool {")
	g.P("	switch req.Path {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		g.P("	case ", `"`+fullPath+`"`, ":")
		g.P("		var msg ", method.Input.GoIdent.GoName)
		g.P("		if err := msg.UnmarshalVT(req.Payload); err != nil {")
		g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 400, Message: err.Error()}}}")
		g.P("			return true")
		g.P("		}")
		g.P()
		if method.Desc.IsStreamingServer() {
			g.P("		if err := handler.", method.GoName, "(ctx, &msg, ch); err != nil {")
			g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 500, Message: err.Error()}}}")
			g.P("		}")
		} else {
			g.P("		resp, err := handler.", method.GoName, "(ctx, &msg)")
			g.P("		if err != nil {")
			g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 500, Message: err.Error()}}}")
			g.P("		} else {")
			g.P("			ch <- &Response{Responses: &Response_RpcResponse{RpcResponse: &RpcResponse{Payload: marshalHelper(resp)}}}")
			g.P("		}")
		}
		g.P("		return true")
	}
	g.P("	}")
	g.P("	return false")
	g.P("}")
	g.P()
}

// generateReverseService generates the client-side caller (Go->Dart) using ReverseCall.
// Only unary methods are supported (no streaming from Go side).
func generateReverseService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName

	g.P("// ", serviceName, "Caller contains generated ReverseCall helpers for ", serviceName, ".")
	g.P("// Each function sends a Push to Dart and waits for a ReverseResponse.")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue // streaming not supported for ReverseService
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		funcName := "Reverse" + strings.TrimSuffix(serviceName, "ReverseService") + method.GoName
		inName := method.Input.GoIdent.GoName
		outName := method.Output.GoIdent.GoName

		g.P("func ", funcName, "(ctx context.Context, req *", inName, ") (*", outName, ", error) {")
		g.P(`	push := &Push{Type: "`, fullPath, `", Payload: marshalHelper(req)}`)
		g.P("	payload, err := reverseCallFn(ctx, push)")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	var resp ", outName)
		g.P("	if err := resp.UnmarshalVT(payload); err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	return &resp, nil")
		g.P("}")
		g.P()
	}
}
