package main

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		sharedEmitted := map[string]bool{}
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, sharedEmitted)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File, sharedEmitted map[string]bool) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0
	hasServices := len(file.Services) > 0

	if !hasServices && !hasPush {
		return
	}

	generateSharedFile(gen, file, sharedEmitted)

	filename := file.GeneratedFilenamePrefix + ".flap.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	if hasServices {
		g.P("import (")
		g.P(`	"context"`)
		g.P(")")
		g.P()
		for _, service := range file.Services {
			generateService(g, service)
		}
	}

	if hasPush {
		emitPushHelpers(g, pushMessages)
	}
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

// emitPushHelpers generates NewPushXxx constructor helpers for each Push-prefixed message.
// Push is now a type-tagged payload (type string + payload bytes), analogous to RpcRequest.
func emitPushHelpers(g *protogen.GeneratedFile, pushMessages []*protogen.Message) {
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		// Full protobuf type name, e.g. "pb.PushNip05"
		fullName := string(msg.Desc.FullName())
		g.P("// New", msgName, " wraps ", msgName, " into a Push message.")
		g.P("func New", msgName, "(msg *", msgName, ") *Push {")
		g.P(`	return &Push{Type: "`, fullName, `", Payload: marshalHelper(msg)}`)
		g.P("}")
		g.P()
	}
}

func generateSharedFile(gen *protogen.Plugin, file *protogen.File, sharedEmitted map[string]bool) {
	// Emit once per output directory (package) to avoid duplicate definitions.
	outDir := path.Dir(file.GeneratedFilenamePrefix)
	if sharedEmitted[outDir] {
		return
	}
	sharedEmitted[outDir] = true

	filename := path.Join(outDir, "marshal_shared.flap.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-flap. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("func marshalHelper(msg interface{ MarshalVT() ([]byte, error) }) []byte {")
	g.P("	b, err := msg.MarshalVT()")
	g.P("	if err != nil {")
	g.P("		panic(err)")
	g.P("	}")
	g.P("	return b")
	g.P("}")
	g.P()
}

func generateService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName
	interfaceName := serviceName + "Handler"

	// 1. Generate Interface
	g.P("// ", interfaceName, " is the server interface for the ", serviceName, " service.")
	g.P("type ", interfaceName, " interface {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue // Not supported yet
		}
		if method.Desc.IsStreamingServer() {
			g.P("	", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ", ch chan<- *Response) error")
		} else {
			g.P("	", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error)")
		}
	}
	g.P("}")
	g.P()

	// 2. Generate Router Section
	g.P("func Handle", serviceName, "(ctx context.Context, req *RpcRequest, ch chan<- *Response, handler ", interfaceName, ") bool {")
	g.P("	switch req.Path {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		g.P("	case ", `"`+fullPath+`"`, ":")
		g.P("		var msg ", method.Input.GoIdent.GoName)
		g.P("		if err := msg.UnmarshalVT(req.Payload); err != nil {")
		g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 400, Message: err.Error()}}}")
		g.P("			return true")
		g.P("		}")
		g.P()
		if method.Desc.IsStreamingServer() {
			g.P("		if err := handler.", method.GoName, "(ctx, &msg, ch); err != nil {")
			g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 500, Message: err.Error()}}}")
			g.P("		}")
		} else {
			g.P("		resp, err := handler.", method.GoName, "(ctx, &msg)")
			g.P("		if err != nil {")
			g.P("			ch <- &Response{Responses: &Response_Error{Error: &Error{Code: 500, Message: err.Error()}}}")
			g.P("		} else {")
			g.P("			ch <- &Response{Responses: &Response_RpcResponse{RpcResponse: &RpcResponse{Payload: marshalHelper(resp)}}}")
			g.P("		}")
		}
		g.P("		return true")
	}
	g.P("	}")
	g.P("	return false")
	g.P("}")
	g.P()
}
